version: '2'
services:
  local:
    container_name: reg-local
    image: zhangsean/registry-mirror
    restart: always
    environment:
      - DELETE_ENABLED=true
    volumes:
      - ~/data/registry:/var/lib/registry
    ports:
      - 5000:5000
  aliyun:
    container_name: reg-aliyun
    image: zhangsean/registry-mirror
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://zzj1next.mirror.aliyuncs.com
    volumes:
      - ~/data/registry:/var/lib/registry
  gcr:
    container_name: reg-gcr
    image: zhangsean/registry-mirror
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://gcr.io
    volumes:
      - ~/data/registry:/var/lib/registry
  k8s:
    container_name: reg-k8s
    image: zhangsean/registry-mirror
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://k8s.gcr.io
    volumes:
      - ~/data/registry:/var/lib/registry
  quay:
    container_name: reg-quay
    image: zhangsean/registry-mirror
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://quay.io
    volumes:
      - ~/data/registry:/var/lib/registry
  ui:
    container_name: reg-ui
    image: zhangsean/registry-ui
    restart: always
    links:
      - local:reg-local
    environment:
      - REGISTRY_API=http://reg-local:5000/v2
      - REGISTRY_WEB=hub.io
      - SHOW_IMAGE_SIZE=true
  nginx:
    container_name: reg-nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    links:
      - ui:reg-ui
      - local:reg-local
      - aliyun:reg-aliyun
      - quay:req-quay
      - gcr:reg-gcr
      - k8s:reg-k8s
    volumes:
      - ./nginx-mirror.conf:/etc/nginx/conf.d/default.conf
